# for docker compose
version: '3.1'

services:
  mongo:
    image: mongo
    container_name: mongo
    volumes:
      - mongodb_storage:/data/db
    restart: always
    ports:
      - 127.0.0.1:12346:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: must
      MONGO_INITDB_ROOT_PASSWORD: must
    networks:
      - inside
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: must
      ME_CONFIG_MONGODB_ADMINPASSWORD: must
      ME_CONFIG_MONGODB_URL: mongodb://must:must@mongo:27017/
    networks:
      - inside
volumes:
    mongodb_storage: {}

networks:
    inside:
      name: mongodb
